notifications: false

sudo: false

jobs:
  include:
    - name: test
      language: php
      php: "7.2"
      install: composer --no-interaction install
      script: ./vendor/bin/phpunit
    - name: test
      language: php
      install: composer --no-interaction update --prefer-lowest
      script: ./vendor/bin/phpunit
